FROM dunglas/frankenphp:latest

WORKDIR /app

# システム依存関係のインストール
RUN apt-get update && apt-get install -y \
    libzip-dev \
    zip \
    unzip \
    gnupg \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Nodeのインストール
RUN curl -sL https://deb.nodesource.com/setup_18.x | bash - \
    && apt-get install -y nodejs \
    && apt-get clean

# PHPの拡張機能のインストール
RUN install-php-extensions \
    pdo_mysql \
    zip \
    opcache \
    pcntl \
    bcmath \
    xdebug

# Composerのインストール
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# プロジェクトファイルのコピー
COPY . .

# 依存関係のインストール
RUN composer install --no-interaction

# .envファイルのコピー
COPY .env.example .env

# NPM依存関係のインストール
RUN npm install

# パーミッションの設定
RUN chown -R www-data:www-data \
    /app/storage \
    /app/bootstrap/cache

# ポートの公開
EXPOSE 80 443 5173

# コンテナ起動時のコマンド
CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=80"] 